# SQLite. Versions 3.8.0 and up are supported.
#   gem install mysql2
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'mysql2'
#

default: &default
  adapter: postgresql
  encoding: utf8
  username: eqalelynuycikh
  password: 78e67ad63e3b0bc06ed4f57d1673affdb3d36c2a4b7ad096b5384877b2879ff9
  pool: 5
  timeout: 5000
  host: ec2-54-145-249-177.compute-1.amazonaws.com
  port: 5432

development:
  <<: *default
  database: GAME_DB_DEV
test:
  <<: *default
  database: GAME_DB_TEST
production:
  <<: *default
  database: GAME_DB_PROD