# SQLite. Versions 3.8.0 and up are supported.
#   gem install mysql2
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'mysql2'
#


# default: &default
#   adapter: postgresql
#   encoding: utf8
#   username: postgres
#   password: root
#   pool: 5
#   timeout: 5000
#   port: 5432

# development:
#   <<: *default
#   database: GAME_DB_DEV
# test:
#   <<: *default
#   database: GAME_DB_TEST
# production:
#   <<: *default
#   database: GAME_DB_PROD



default: &default
  adapter: postgresql
  encoding: utf8
  username: vmkswmrhjzhdvp
  password: bf947349bc24fd93a50d7e134a45d49d657e0d26c83301f811e7b84aabd8bf54
  pool: 5
  timeout: 5000
  host: ec2-34-198-31-223.compute-1.amazonaws.com
  port: 5432

development:
  <<: *default
  database: ddqkmut8d9a7bs
production:
  <<: *default
  database: ddqkmut8d9a7bs







# default: &default
#   adapter: mysql2
#   pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
#   timeout: 5000
#   username: root
#   password: 123
#   encoding: utf8

# development:
#   <<: *default
#   database: GAME_DB_DEV
# test:
#   <<: *default
#   database: GAME_DB_TEST
# production:
#   <<: *default
#   database: GAME_DB_PROD