# SQLite. Versions 3.8.0 and up are supported.
#   gem install mysql2
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'mysql2'
#

default: &default
  adapter: postgresql
  encoding: utf8
  username: <%= ENV['POSTGRES_USER'] %>
  password: <%= ENV['POSTGRES_PASSWORD'] %>
  pool: 5
  timeout: 5000
  # host: <%= ENV['POSTGRES_HOST'] %>

development:
  <<: *default
  database: GAME_DB_DEV
test:
  <<: *default
  database: GAME_DB_TEST
production:
  <<: *default
  database: GAME_DB_PROD